### ISSUE TITLE
Use if __name__ == '__main__':

### ISSUE THREAD

**Issue by k4nuck** [mmcgrath424/practice#7]
https://github.com/mmcgrath424/practice/blob/45687179abf1734bfdc75e5b5716b007eacd4458/LinkedList.py#L86

**Comment by k4nuck** [comment]
By putting your test code in
if __name__ == '__main__':
You can leave it there so that you can test your stuff but if other python code imports this module then your test cases will properly be ignored.  Right now you will need to delete it I believe before it would work if you were to import your file

**Comment by mmcgrath424** [comment]
fixed
